import Foundation

/// でんきデッキ作成
struct ElectricDeckCreator : IDeckCreator {
    
    func create() -> [Card] {
        return [Card(number: "037551", category: .Pokemon),
                Card(number: "037551", category: .Pokemon),
                Card(number: "037551", category: .Pokemon),
                Card(number: "037552", category: .Pokemon),
                Card(number: "037552", category: .Pokemon),
                Card(number: "037553", category: .Pokemon),
                Card(number: "037554", category: .Pokemon),
                Card(number: "037554", category: .Pokemon),
                Card(number: "037555", category: .Pokemon),
                Card(number: "037556", category: .Pokemon),
                Card(number: "037557", category: .Pokemon),
                Card(number: "037557", category: .Pokemon),
                Card(number: "037557", category: .Pokemon),
                Card(number: "037558", category: .Pokemon),
                Card(number: "037558", category: .Pokemon),
                Card(number: "037559", category: .Pokemon),
                Card(number: "037560", category: .Pokemon),
                Card(number: "037561", category: .Pokemon),
                Card(number: "037562", category: .Goods),
                Card(number: "037563", category: .Goods),
                Card(number: "037564", category: .Goods),
                Card(number: "037564", category: .Goods),
                Card(number: "037565", category: .Goods),
                Card(number: "037565", category: .Goods),
                Card(number: "037566", category: .Goods),
                Card(number: "037566", category: .Goods),
                Card(number: "037567", category: .Goods),
                Card(number: "037567", category: .Goods),
                Card(number: "037568", category: .Goods),
                Card(number: "037569", category: .Goods),
                Card(number: "037570", category: .Support),
                Card(number: "037570", category: .Support),
                Card(number: "037570", category: .Support),
                Card(number: "037571", category: .Support),
                Card(number: "037572", category: .Support),
                Card(number: "037572", category: .Support),
                Card(number: "037573", category: .Support),
                Card(number: "037573", category: .Support),
                Card(number: "037573", category: .Support),
                Card(number: "037573", category: .Support),
                Card(number: "037574", category: .Support),
                Card(number: "037574", category: .Support),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
                Card(number: "000004", category: .Energy),
               ]
    }
}
