import Foundation

struct FightingDeckCreator : IDeckCreator {
    func create() -> [Card] {
        return [Card(number: "037576", category: .Pokemon),
                Card(number: "037576", category: .Pokemon),
                Card(number: "037576", category: .Pokemon),
                Card(number: "037577", category: .Pokemon),
                Card(number: "037577", category: .Pokemon),
                Card(number: "037578", category: .Pokemon),
                Card(number: "037579", category: .Pokemon),
                Card(number: "037580", category: .Pokemon),
                Card(number: "037581", category: .Pokemon),
                Card(number: "037581", category: .Pokemon),
                Card(number: "037582", category: .Pokemon),
                Card(number: "037583", category: .Pokemon),
                Card(number: "037583", category: .Pokemon),
                Card(number: "037583", category: .Pokemon),
                Card(number: "037584", category: .Pokemon),
                Card(number: "037584", category: .Pokemon),
                Card(number: "037585", category: .Pokemon),
                Card(number: "037586", category: .Pokemon),
                Card(number: "037587", category: .Goods),
                Card(number: "037588", category: .Goods),
                Card(number: "037589", category: .Goods),
                Card(number: "037589", category: .Goods),
                Card(number: "037590", category: .Goods),
                Card(number: "037591", category: .Goods),
                Card(number: "037591", category: .Goods),
                Card(number: "037592", category: .Goods),
                Card(number: "037592", category: .Goods),
                Card(number: "037593", category: .Goods),
                Card(number: "037593", category: .Goods),
                Card(number: "037594", category: .Goods),
                Card(number: "037595", category: .Goods),
                Card(number: "037595", category: .Goods),
                Card(number: "037595", category: .Goods),
                Card(number: "037596", category: .Goods),
                Card(number: "037596", category: .Goods),
                Card(number: "037597", category: .Goods),
                Card(number: "037598", category: .Goods),
                Card(number: "037598", category: .Goods),
                Card(number: "037598", category: .Goods),
                Card(number: "037598", category: .Goods),
                Card(number: "037599", category: .Goods),
                Card(number: "037599", category: .Goods),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
                Card(number: "000006", category: .Energy),
               ]
    }
}
