import Foundation

/// ほのおデッキ作成
struct FireDeckCreator : IDeckCreator  {
    
    func create() -> [Card] {
        return [Card(number: "037503", category: .Pokemon),
                Card(number: "037503", category: .Pokemon),
                Card(number: "037504", category: .Pokemon),
                Card(number: "037505", category: .Pokemon),
                Card(number: "037506", category: .Pokemon),
                Card(number: "037506", category: .Pokemon),
                Card(number: "037507", category: .Pokemon),
                Card(number: "037508", category: .Pokemon),
                Card(number: "037508", category: .Pokemon),
                Card(number: "037508", category: .Pokemon),
                Card(number: "037509", category: .Pokemon),
                Card(number: "037509", category: .Pokemon),
                Card(number: "037509", category: .Pokemon),
                Card(number: "037510", category: .Pokemon),
                Card(number: "037510", category: .Pokemon),
                Card(number: "037511", category: .Pokemon),
                Card(number: "037511", category: .Pokemon),
                Card(number: "037512", category: .Pokemon),
                Card(number: "037513", category: .Goods),
                Card(number: "037514", category: .Goods),
                Card(number: "037515", category: .Goods),
                Card(number: "037516", category: .Goods),
                Card(number: "037516", category: .Goods),
                Card(number: "037517", category: .Goods),
                Card(number: "037518", category: .Goods),
                Card(number: "037518", category: .Goods),
                Card(number: "037519", category: .Goods),
                Card(number: "037519", category: .Goods),
                Card(number: "037520", category: .Goods),
                Card(number: "037520", category: .Goods),
                Card(number: "037521", category: .Goods),
                Card(number: "037522", category: .Support),
                Card(number: "037522", category: .Support),
                Card(number: "037522", category: .Support),
                Card(number: "037523", category: .Support),
                Card(number: "037523", category: .Support),
                Card(number: "037524", category: .Support),
                Card(number: "037524", category: .Support),
                Card(number: "037524", category: .Support),
                Card(number: "037524", category: .Support),
                Card(number: "037525", category: .Support),
                Card(number: "037525", category: .Support),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
                Card(number: "000002", category: .Energy),
               ]
    }
}
