import Foundation

// くさデッキ作成
struct GlassDeckCreator : IDeckCreator {
    
    func create() -> [Card] {
        return [Card(number: "037479", category: .Pokemon),
                Card(number: "037480", category: .Pokemon),
                Card(number: "037480", category: .Pokemon),
                Card(number: "037481", category: .Pokemon),
                Card(number: "037481", category: .Pokemon),
                Card(number: "037482", category: .Pokemon),
                Card(number: "037483", category: .Pokemon),
                Card(number: "037483", category: .Pokemon),
                Card(number: "037484", category: .Pokemon),
                Card(number: "037484", category: .Pokemon),
                Card(number: "037484", category: .Pokemon),
                Card(number: "037485", category: .Pokemon),
                Card(number: "037485", category: .Pokemon),
                Card(number: "037485", category: .Pokemon),
                Card(number: "037486", category: .Pokemon),
                Card(number: "037486", category: .Pokemon),
                Card(number: "037487", category: .Pokemon),
                Card(number: "037488", category: .Pokemon),
                Card(number: "037489", category: .Goods),
                Card(number: "037490", category: .Goods),
                Card(number: "037491", category: .Goods),
                Card(number: "037492", category: .Goods),
                Card(number: "037492", category: .Goods),
                Card(number: "037493", category: .Goods),
                Card(number: "037493", category: .Goods),
                Card(number: "037494", category: .Goods),
                Card(number: "037494", category: .Goods),
                Card(number: "037495", category: .Goods),
                Card(number: "037495", category: .Goods),
                Card(number: "037496", category: .Goods),
                Card(number: "037497", category: .Support),
                Card(number: "037497", category: .Support),
                Card(number: "037497", category: .Support),
                Card(number: "037498", category: .Support),
                Card(number: "037498", category: .Support),
                Card(number: "037499", category: .Support),
                Card(number: "037500", category: .Support),
                Card(number: "037501", category: .Support),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
                Card(number: "000001", category: .Energy),
       ]
    }
}
