import Foundation

/// みずデッキ作成
struct WaterDeckCreator : IDeckCreator {
    
    func create() -> [Card] {
        return [Card(number: "037527", category: .Pokemon),
                Card(number: "037527", category: .Pokemon),
                Card(number: "037528", category: .Pokemon),
                Card(number: "037529", category: .Pokemon),
                Card(number: "037530", category: .Pokemon),
                Card(number: "037530", category: .Pokemon),
                Card(number: "037531", category: .Pokemon),
                Card(number: "037532", category: .Pokemon),
                Card(number: "037533", category: .Pokemon),
                Card(number: "037533", category: .Pokemon),
                Card(number: "037533", category: .Pokemon),
                Card(number: "037534", category: .Pokemon),
                Card(number: "037534", category: .Pokemon),
                Card(number: "037534", category: .Pokemon),
                Card(number: "037535", category: .Pokemon),
                Card(number: "037535", category: .Pokemon),
                Card(number: "037536", category: .Pokemon),
                Card(number: "037536", category: .Pokemon),
                Card(number: "037537", category: .Goods),
                Card(number: "037538", category: .Goods),
                Card(number: "037539", category: .Goods),
                Card(number: "037540", category: .Goods),
                Card(number: "037541", category: .Goods),
                Card(number: "037541", category: .Goods),
                Card(number: "037542", category: .Goods),
                Card(number: "037542", category: .Goods),
                Card(number: "037543", category: .Goods),
                Card(number: "037543", category: .Goods),
                Card(number: "037544", category: .Goods),
                Card(number: "037544", category: .Goods),
                Card(number: "037545", category: .Support),
                Card(number: "037546", category: .Support),
                Card(number: "037546", category: .Support),
                Card(number: "037546", category: .Support),
                Card(number: "037547", category: .Support),
                Card(number: "037547", category: .Support),
                Card(number: "037548", category: .Support),
                Card(number: "037548", category: .Support),
                Card(number: "037548", category: .Support),
                Card(number: "037548", category: .Support),
                Card(number: "037549", category: .Support),
                Card(number: "037549", category: .Support),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
                Card(number: "000003", category: .Energy),
               ]
    }
}
